
#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TBrowser.h"
#include "TH2.h"
#include "TRandom.h"


void oneDtwoD()
{
   //read the Tree generated by tree1w and fill two histograms


	remove ("test.root");

   TFile *f1 = new TFile("test_proton_si001ax_100K_40um_cry.root");
   TFile *f2 = new TFile("test.root","NEW");

   TTree *t2 = new TTree("tree", "simple tree");

   TTree *t1 = (TTree*)f1->Get("sim");

   TLeaf *angX = t1->GetLeaf("angXout");
   TLeaf *angY = t1->GetLeaf("angYout");

   Double_t angXout;
   TH1F *hpx   = new TH1F("hpx","angXout",1000,-17,17);
   TH1F *hpy   = new TH1F("hpy","angYout",1000,-17,17);
   TH2D *histo = new TH2D("Histo","Ang_distribution", 1000, -17, 17, 1000, -17, 17);
   t2->Branch("hpx","TH1F",&hpx);
   t2->Branch("hpy","TH1F",&hpy);
   t2->Branch("Histo","TH2D",&histo);

   //create two histograms

   //read all entries and fill the histograms
   Long64_t nentries = t1->GetEntries();
   //cout << " number of entries " << nentries << endl;
   for (Long64_t i=0;i<nentries;i++) {
     //leaf->GetEntry(i);
     angX->GetBranch()->GetEntry(i);
     angY->GetBranch()->GetEntry(i);
     hpx->Fill(angX->GetValue());
     hpy->Fill(angY->GetValue());
     histo->Fill(angX->GetValue(),angY->GetValue());
  }
  hpx->Write();
  hpy->Write();
  histo->Write();

  histo->Draw(); // nupiesia histo gerai.



  if (gROOT->IsBatch()) return;

}
